import Navbar from "./components/Navbar";  
export const metadata = {
  title: "AAJ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Navbar Component */}
        <Navbar />
        
        {/* Main content (children will be rendered here) */}
        <main>{children}</main>
      </body>
    </html>
  );
}
