import Navbar from "./components/Navbar";  
import Footer from "./components/Footer";
export const metadata = {
  title: "AAJ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Navbar Component */}
        <Navbar />
        
        {/* Main content (children will be rendered here) */}
        <main>{children}</main>

        {/* Footer Component */}
        <Footer />
      </body>
    </html>
  );
}
